'use client';
import {useEffect,useRef,useState} from 'react';
import {HandLandmarker,FilesetResolver} from '@mediapipe/tasks-vision';
import {Camera,CameraOff,Hand,Lightbulb,RotateCcw,Star,SwitchCamera,Zap} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
export default function Home(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),detector=useRef<HandLandmarker|null>(null),raf=useRef(0),battery=useRef<HTMLButtonElement>(null),lastToggle=useRef(0);
 const [cam,setCam]=useState(false),[tracking,setTracking]=useState(false),[finger,setFinger]=useState<{x:number,y:number}|null>(null),[facing,setFacing]=useState<'user'|'environment'>('environment'),[error,setError]=useState(''),[on,setOn]=useState(false),[power,setPower]=useState(3),[stars,setStars]=useState(0),[pos,setPos]=useState({x:0,y:0});
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());cancelAnimationFrame(raf.current);detector.current?.close()},[]);
 function toggle(){setOn(v=>{if(!v)setStars(s=>s+1);return !v})}
 async function prepareHands(){if(detector.current)return detector.current;setTracking(false);const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm');detector.current=await HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:1,minHandDetectionConfidence:.55,minTrackingConfidence:.55});setTracking(true);return detector.current}
 async function trackHands(){const d=await prepareHands();let last=-1;const loop=()=>{const v=video.current;if(v&&v.readyState>=2&&v.currentTime!==last){last=v.currentTime;const result=d.detectForVideo(v,performance.now());const tip=result.landmarks[0]?.[8];if(tip){const point={x:tip.x*innerWidth,y:tip.y*innerHeight};setFinger(point);const r=battery.current?.getBoundingClientRect();if(r&&point.x>r.left-35&&point.x<r.right+35&&point.y>r.top-35&&point.y<r.bottom+35&&performance.now()-lastToggle.current>1200){lastToggle.current=performance.now();toggle()}}else setFinger(null)}raf.current=requestAnimationFrame(loop)};cancelAnimationFrame(raf.current);loop()}
 async function startCamera(mode:'user'|'environment'){stream.current?.getTracks().forEach(t=>t.stop());cancelAnimationFrame(raf.current);try{setError('');let s:MediaStream;try{s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:mode},width:{ideal:1280},height:{ideal:720}},audio:false})}catch{s=await navigator.mediaDevices.getUserMedia({video:true,audio:false})}stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}setFacing(mode);setCam(true);trackHands().catch(()=>setError('La cámara funciona, pero no pude cargar el detector de dedos.'))}catch{setCam(false);setError('No pude abrir la cámara. Revisa el permiso del navegador.')}}
 async function openCamera(){if(stream.current){stream.current.getTracks().forEach(t=>t.stop());stream.current=null;cancelAnimationFrame(raf.current);setFinger(null);setTracking(false);if(video.current)video.current.srcObject=null;setCam(false);return}await startCamera(innerWidth<700?'environment':'user')}
 async function switchCamera(){await startCamera(facing==='environment'?'user':'environment')}
 function drag(e:React.PointerEvent<HTMLDivElement>){if(e.buttons===1)setPos(p=>({x:p.x+e.movementX,y:p.y+e.movementY}))}
 return <main className={`ar-page ${on?'is-on':''}`}><video ref={video} muted playsInline className={`camera-feed ${cam?'show':''}`}/><div className={`camera-fallback ${cam?'hide':''}`}/><header><div className="brand"><span><Zap/></span><div><h1>Electricidad mágica AR</h1><p>Apunta con tu dedo índice</p></div></div><div className="score"><Star fill="currentColor"/> {stars}</div></header><div className="camera-tools"><button onClick={openCamera}>{cam?<CameraOff/>:<Camera/>}{cam?'Cerrar cámara':'Abrir cámara'}</button>{cam&&<button className="switch-camera" onClick={switchCamera}><SwitchCamera/> Cambiar</button>}<span>{tracking?'Detector de dedo listo':'Preparando detector…'}</span></div><section className="ar-space" onPointerMove={drag}><div className="scan-corners"/><div className="ar-board-kid" style={{transform:`translate(${pos.x}px,${pos.y}px) rotateX(55deg)`}}><div className="board-label"><Hand/> APUNTA AQUÍ CON TU DEDO</div><div className={`wire top ${on?'live':''}`}/><div className={`wire bottom ${on?'live':''}`}/><button ref={battery} className={`battery ${on?'active':''}`} onClick={toggle}><span>+</span><Zap fill="currentColor"/><b>BATERÍA</b><small>APUNTA AQUÍ</small></button><div className="path-dots">{Array.from({length:7},(_,i)=><i key={i}/>)}</div><button className={`bulb ${on?'glow':''}`} onClick={toggle}><span className="rays">✦</span><Lightbulb fill={on?'#ffe266':'#dfe7ff'}/><b>{on?'¡BRILLA!':'FOCO'}</b></button></div><div className="ar-message"><span>{finger?'☝️':'🖐️'}</span><p><b>{finger?'¡Veo tu dedo!':'Muestra tu mano'}</b><br/>{finger?'Acércalo a la batería.':'con el índice levantado.'}</p></div></section>{finger&&<div className="finger-dot" style={{left:finger.x,top:finger.y}}><span/></div>}<section className="bottom-panel"><div className="power-control"><div><b>Fuerza</b><span>{'⚡'.repeat(power)}</span></div><Slider min={1} max={5} step={1} value={[power]} onValueChange={v=>setPower(v[0])}/></div><button className={`main-action ${on?'stop':''}`} onClick={toggle}>{on?'Apagar':'Encender'}</button><button className="reset" onClick={()=>{setOn(false);setPower(3);setStars(0);setPos({x:0,y:0})}}><RotateCcw/> Reiniciar</button></section>{error&&<div className="error">{error}</div>}</main>
}
