'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,CameraOff,CirclePower,RotateCcw,Zap} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';

export default function Home(){
 const video=useRef<HTMLVideoElement>(null), stream=useRef<MediaStream|null>(null);
 const [cam,setCam]=useState(false),[error,setError]=useState(''),[on,setOn]=useState(true),[volts,setVolts]=useState(5),[hz,setHz]=useState(300),[tilt,setTilt]=useState({x:0,y:0});
 useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
 async function camera(){if(stream.current){stream.current.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setCam(false);return}try{setError('');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}setCam(true)}catch{setError('No se pudo abrir la cámara. Puedes continuar en modo demo.')}}
 const points=Array.from({length:55},(_,i)=>`${i*6},${54+Math.sin(i/54*Math.PI*2*(2+hz/260))*(on?volts*6.2:0)}`).join(' ');
 return <main className="min-h-screen bg-[#05090f] text-white"><header className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl border border-cyan-300/30 bg-cyan-300/10 text-cyan-300"><Zap className="size-5"/></span><div><h1 className="font-semibold">Circuito AR</h1><p className="text-xs text-slate-400">Laboratorio interactivo</p></div></div><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1.5 text-xs text-emerald-300">Demo independiente</span></header>
 <section className="mx-auto grid max-w-[1500px] gap-5 px-5 pb-6 sm:px-8 lg:grid-cols-[minmax(0,1fr)_330px]"><div className="stage relative min-h-[540px] overflow-hidden rounded-[28px] border border-white/10 bg-slate-950" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setTilt({x:(e.clientY/r.height-.5)*-8,y:(e.clientX/r.width-.5)*10})}} onPointerLeave={()=>setTilt({x:0,y:0})}><video ref={video} muted playsInline className={`absolute inset-0 h-full w-full object-cover ${cam?'opacity-65':'opacity-0'}`}/><div className={`demo-grid absolute inset-0 ${cam?'opacity-30':''}`}/><div className="absolute inset-x-0 top-0 z-20 flex justify-between p-5"><span className="rounded-full bg-black/50 px-3 py-2 text-xs text-slate-300">{cam?'Cámara activa · apunta a una superficie':'Modo demo · activa la cámara cuando quieras'}</span><Button onClick={camera} className="rounded-full bg-white text-slate-950 hover:bg-cyan-100">{cam?<CameraOff/>:<Camera/>}{cam?'Cerrar':'Usar cámara'}</Button></div>
 <div className="absolute inset-0 grid place-items-center px-4 pt-16"><div className="board aspect-[1.42/1] w-[min(760px,92%)] rounded-[26px] border border-cyan-200/25 bg-[#091522]/95 p-5 shadow-2xl transition-transform sm:p-7" style={{transform:`perspective(950px) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)`}}><div className="mb-4 flex justify-between"><div><p className="text-[11px] font-bold tracking-[.18em] text-cyan-300">PLACA EXPERIMENTAL</p><p className="mt-1 text-xs text-slate-400">Circuito RLC en serie</p></div><span className={`h-fit rounded-full px-3 py-1.5 text-xs ${on?'bg-emerald-400/15 text-emerald-300':'bg-slate-700 text-slate-400'}`}>{on?'● ENERGIZADO':'○ APAGADO'}</span></div><div className="grid h-[calc(100%-58px)] gap-4 sm:grid-cols-[1.15fr_.85fr]"><div className="rounded-2xl border border-white/10 bg-[#050b12] p-4"><span className="text-[10px] tracking-widest text-slate-500">SEÑAL DE ENTRADA</span><svg viewBox="0 0 324 108" className="mt-5 w-full"><defs><pattern id="g" width="18" height="18" patternUnits="userSpaceOnUse"><path d="M18 0H0V18" fill="none" stroke="#173044"/></pattern></defs><rect width="324" height="108" fill="url(#g)"/><line x1="0" y1="54" x2="324" y2="54" stroke="#31506a"/><polyline points={points} fill="none" stroke={on?'#43e8ff':'#536273'} strokeWidth="3"/></svg><div className="flex justify-between font-mono text-xs"><b className="text-cyan-300">{on?volts:0}.0 V</b><span className="text-slate-400">{hz} Hz</span></div></div><div className="relative rounded-2xl border border-white/10 bg-[#07101a] p-4"><span className={`absolute left-[13%] top-1/2 h-0.5 w-[74%] ${on?'wire':'bg-slate-700'}`}/><div className="relative z-10 flex h-full items-center justify-between gap-2"><Part c="cyan" name="FUENTE" val={`${volts} V`} icon="~" on={on}/><Part c="amber" name="R" val="220 Ω" icon="R" on={on}/><Part c="violet" name="C" val="10 μF" icon="Ⅱ" on={on}/></div></div></div></div></div>{error&&<p className="absolute bottom-4 left-1/2 z-30 w-[90%] -translate-x-1/2 rounded-xl bg-rose-500 px-4 py-3 text-center text-sm">{error}</p>}</div>
 <aside className="rounded-[28px] border border-white/10 bg-[#0b121c] p-6"><div className="mb-7 flex justify-between"><div><h2 className="font-semibold">Panel de control</h2><p className="mt-1 text-xs text-slate-500">Cambios en tiempo real</p></div><Button variant="ghost" size="icon" onClick={()=>{setVolts(5);setHz(300);setOn(true)}} aria-label="Restablecer"><RotateCcw/></Button></div><Control label="Voltaje" value={`${volts} V`} hint="Amplitud de la señal"><Slider min={1} max={10} step={1} value={[volts]} onValueChange={v=>setVolts(v[0])}/></Control><Control label="Frecuencia" value={`${hz} Hz`} hint="Velocidad de oscilación"><Slider min={50} max={1000} step={50} value={[hz]} onValueChange={v=>setHz(v[0])}/></Control><button onClick={()=>setOn(!on)} className={`mt-3 flex w-full items-center justify-between rounded-2xl border p-4 text-left ${on?'border-emerald-400/30 bg-emerald-400/10':'border-white/10 bg-white/[.03]'}`}><span><b className="block text-sm">Alimentación</b><small className="text-slate-400">{on?'Circuito funcionando':'Sin corriente'}</small></span><CirclePower className={on?'text-emerald-300':'text-slate-500'}/></button><div className="mt-6 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.06] p-4 text-sm leading-7 text-slate-300"><b className="text-xs tracking-wider text-cyan-300">CÓMO PROBARLO</b><p className="mt-2">01 · Activa la cámara.<br/>02 · Apunta a una mesa.<br/>03 · Mueve los controles.</p></div></aside></section></main>
}
function Control({label,value,hint,children}:{label:string,value:string,hint:string,children:React.ReactNode}){return <div className="mb-7"><div className="mb-3 flex justify-between"><span><b className="block text-sm">{label}</b><small className="text-slate-500">{hint}</small></span><output className="font-mono text-sm font-bold text-cyan-300">{value}</output></div>{children}</div>}
function Part({c,name,val,icon,on}:{c:string,name:string,val:string,icon:string,on:boolean}){const x:Record<string,string>={cyan:'border-cyan-300/50 bg-cyan-300/15 text-cyan-200',amber:'border-amber-300/50 bg-amber-300/15 text-amber-200',violet:'border-violet-300/50 bg-violet-300/15 text-violet-200'};return <div className={`flex min-w-0 flex-1 flex-col items-center gap-2 ${on?'':'opacity-50'}`}><span className={`grid size-14 place-items-center rounded-2xl border text-xl font-bold ${x[c]}`}>{icon}</span><span className="bg-[#07101a] px-1 text-center"><b className="block text-[9px] text-slate-500">{name}</b><small className="whitespace-nowrap font-mono text-[10px]">{val}</small></span></div>}
